import ComingSoon from '../../../public/assets/congregations/ComingSoon.webp'
import AdatHallel from '../../../public/assets/congregations/AdatHallel.webp'
import BethSarShalom from '../../../public/assets/congregations/BethSarShalom.webp'
import AdatYeshua from '../../../public/assets/congregations/AdatYeshua.webp'
import Ohav from '../../../public/assets/congregations/Ohav.webp'
import MatsuValley from '../../../public/assets/congregations/MatsuValley.webp'
import BethEmunah from '../../../public/assets/congregations/BethEmunah.webp'
import AHavBShemYeshua from '../../../public/assets/congregations/AHavBShemYeshua.webp'
import ShilohMessianic from '../../../public/assets/congregations/ShilohMessianic.webp'
import BethDavid from '../../../public/assets/congregations/BethDavid.webp'
import TempleAvivJudea from '../../../public/assets/congregations/TempleAvivJudea.webp'
//! import BeitDavid from '../../../public/assets/congregations/Ohav.webp'
import BenDavid from '../../../public/assets/congregations/BenDavid.webp'
import KehilatAriel from '../../../public/assets/congregations/KehilatAriel.webp'
import TreeOfLife from '../../../public/assets/congregations/TreeOfLife.webp'
export const congregations = [
  {
    name: 'Adat Hallel Messianic Congregation',
    city: 'Irvine',
    state: 'California',
    country: 'United States',
    url: 'https://https://facebook.com/Adat.Hallel.Messianic/',
    phone: '',
    email: 'office@myadat.com',
    img: AdatHallel,
  },
  {
    name: 'Congregation Beth Sar Shalom',
    city: 'Tuscon',
    state: 'Arizona',
    country: 'United States',
    url: 'https://https://facebook.com/CBSSTucson/',
    phone: '(520) 326-2020',
    email: 'office@shalomtucson.org',
    img: BethSarShalom,
  },
  {
    name: "Adat Y'shua Messianic Congregation",
    city: 'West Hills',
    state: 'California',
    country: 'United States',
    url: 'https://adatyshua.org/',
    phone: ' (818) 222-0200',
    email: '',
    img: AdatYeshua,
  },
  {
    name: 'Matsu Valley Messianic Congregation',
    city: 'Wasilla',
    state: 'Alaska',
    country: 'United States',
    url: 'https://adatyshua.org/',
    phone: '',
    email: 'matsuvalleymessianic@gmail.com',
    img: MatsuValley,
  },
  {
    name: 'Ohav Shalom Messianic Congregation',
    city: 'Cathedral City',
    state: 'California',
    country: 'United States',
    url: 'https://ohavshalomministries.org/',
    phone: '(760) 668-5966',
    email: 'info@ohavshalomministries.org',
    img: Ohav,
  },
  {
    name: 'Beth Emunah Messianic Synagogue',
    city: 'Agoura Hills',
    state: 'California',
    country: 'United States',
    url: 'https://bethemunah.org',
    phone: '(818) 597-9700',
    email: 'office@bethemunah.org',
    img: BethEmunah,
  },
  {
    name: 'Ahava B’Shem Yeshua',
    city: 'Prescott',
    state: 'Arizona',
    country: 'United States',
    url: 'https://ahavabshemyeshua.com',
    phone: '(928) 443-5988',
    email: 'office@ahavabshemyeshua.com',
    img: AHavBShemYeshua,
  },
  {
    name: 'Shiloh Messianic Congregation',
    city: 'Redlands',
    state: 'California',
    country: 'United States',
    url: 'https://shilohmessianic.com',
    phone: '(909) 338-4846',
    email: 'shilohcongregation@gmail.com',
    img: ShilohMessianic,
  },
  {
    name: 'Beth David Messianic Congregation',
    city: 'Fresno',
    state: 'California',
    country: 'United States',
    url: 'https://bethdavidmc.org',
    phone: '(559) 435-0106',
    email: 'info@bethdavidmc.org',
    img: BethDavid,
  },

  {
    name: 'Temple Aviv Judea',
    city: 'Fullerton',
    state: 'California',
    country: 'United States',
    url: 'https://avivjudea.org',
    phone: '(714) 748-4504',
    email: 'info@avivjudea.org',
    img: TempleAvivJudea,
  },
  {
    name: 'Beit David Messianic Fellowship',
    city: 'Long Beach',
    state: 'California',
    country: 'United States',
    url: 'https://Beit-David.org',
    phone: '',
    email: 'beit.david@yahoo.com',
    img: ComingSoon,
  },
  {
    name: 'Ben David Messianic Jewish Congregation',
    city: 'Orange',
    state: 'California',
    country: 'United States',
    url: 'https://bendavidmjc.com/',
    phone: '(949) 551-2659',
    email: 'info@BenDavidMJC.org',
    img: BenDavid,
  },
  {
    name: 'Kehilat Ariel',
    city: 'San Diego',
    state: 'California',
    country: 'United States',
    url: 'https://kehilatariel.org',
    phone: '(858) 430-6433',
    email: '',
    img: KehilatAriel,
  },
  {
    name: 'Tree of Life Messianic Congregation',
    city: 'San Diego',
    state: 'California',
    country: 'United States',
    url: 'https://.treeoflifeca.org',
    phone: '',
    email: 'ravjoel@pacbell.net',
    img: TreeOfLife,
  },

  {
    name: 'Congregation Roeh Israel',
    city: 'Denver',
    state: 'Colorado',
    country: 'United States',
    url: 'https://roehisrael.com',
    phone: '(303) 337-6254',
    email: 'roehisraeldenver@gmail.com',
    img: ComingSoon,
  },
  {
    name: 'Congregation Yeshuat Tsion',
    city: 'Greenwood Village',
    state: 'Colorado',
    country: 'United States',
    url: 'https://yeshuattsion.org',
    phone: '(303) 740-5413',
    email: '',
    img: ComingSoon,
  },
  {
    name: 'Congregation Simchat Yisrael',
    city: 'West Haven',
    state: 'Connecticut',
    country: 'United States',
    url: 'https://simchatyisrael.org',
    phone: '(203) 932-9929',
    email: 'office@simchatyisrael.org',
    img: ComingSoon,
  },
  {
    name: 'Ohr Chadash',
    city: 'Clearwater',
    state: 'Florida',
    country: 'United States',
    url: 'https://ohrchadash.org',
    phone: '(727) 726-1472',
    email: '',
    img: ComingSoon,
  },
  {
    name: 'Temple Aron HaKodesh',
    city: 'Fort Lauderdale',
    state: 'Florida',
    country: 'United States',
    url: 'https://tak.org',
    phone: '(954) 485-8491',
    email: '',
    img: ComingSoon,
  },
  {
    name: 'Etz Chayim Messianic Synagogue',
    city: 'Lakeland',
    state: 'Florida',
    country: 'United States',
    url: 'https://myetzchayim.org',
    phone: '(863) 274-6141',
    email: '',
    img: ComingSoon,
  },

  {
    name: 'Mishkan Messianic Congregation',
    city: 'Ocala',
    state: 'Florida',
    country: 'United States',
    url: '',
    phone: '(352) 687-4434',
    email: 'mishkanmessianiccongregation@yahoo.com',
    img: ComingSoon,
  },
  {
    name: 'Kerem El Messianic Synagogue',
    city: 'Port St. Lucie',
    state: 'California',
    country: 'United States',
    url: 'https://keremel.org',
    phone: '(772) 621-7812',
    email: '',
    img: ComingSoon,
  },
  {
    name: 'Shoresh David Messianic Synagogue',
    city: 'St Petersburg',
    state: 'California',
    country: 'United States',
    url: 'https://shoreshdavid.org',
    phone: '(813) 831-5673',
    email: '',
    img: ComingSoon,
  },
  {
    name: 'Shoresh David Messianic Synagogue',
    city: 'Tampa',
    state: 'Florida',
    country: 'United States',
    url: 'https://shoreshdavid.org',
    phone: '(813) 760-3269',
    email: '',
    img: ComingSoon,
  },
  {
    name: 'Shoresh David Messianic Synagogue',
    city: 'Wesley Chapel',
    state: 'California',
    country: 'United States',
    url: 'https://shoreshdavid.org',
    phone: '(813) 760-3269',
    email: 'emarvin@shoreshdavid.org',
    img: ComingSoon,
  },
  {
    name: 'Congregation Beth Hallel',
    city: 'Roswell',
    state: 'Georgia',
    country: 'United States',
    url: 'https://bethhallel.org',
    phone: '(770) 641-3000',
    email: 'emarvin@shoreshdavid.org',
    img: ComingSoon,
  },
  {
    name: 'Beit Shalom Messianic Synagogue',
    city: 'Thomasville',
    state: 'Georgia',
    country: 'United States',
    url: 'https://beitshalom.us',
    phone: '(229) 327-6060',
    email: 'info.bsms.ga@gmail.com',
    img: ComingSoon,
  },
  {
    name: 'Tikvat Yisrael',
    city: 'Honolulu',
    state: 'Hawaii',
    country: 'United States',
    url: 'https://TikvatYisrael.com',
    phone: '(808) 351-6364',
    email: '',
    img: ComingSoon,
  },
  {
    name: 'The Bridge Messianic Fellowship',
    city: 'Boise',
    state: 'Idaho',
    country: 'United States',
    url: 'https://thebridgeidaho.com',
    phone: '(208) 994-3642',
    email: 'hello@thebridgeidaho.com',
    img: ComingSoon,
  },
  {
    name: 'Rock of Israel Messianic Congregation',
    city: 'Long Grove',
    state: 'Illinois',
    country: 'United States',
    url: 'https://rockofisrael.net',
    phone: '(847) 507-4260',
    email: 'rschwarcz@chosenpeople.com',
    img: ComingSoon,
  },
  {
    name: 'Olive Tree Congregation',
    city: 'Prospect Heights',
    state: 'Illinois',
    country: 'United States',
    url: 'https://olive-tree.org',
    phone: '(847) 222-1230',
    email: 'olivetreechicago@gmail.com',
    img: ComingSoon,
  },
  {
    name: 'Congregation Shaarey Yeshua',
    city: 'Indianapolis',
    state: 'Indiana',
    country: 'United States',
    url: 'https://shaareyyeshua.org',
    phone: '(327) 202-0789',
    email: 'office@shaareyyeshua.org',
    img: ComingSoon,
  },

  {
    name: 'Or HaOlam Messianic Synagogue',
    city: 'Overland Park',
    state: 'Kansas',
    country: 'United States',
    url: '',
    phone: '(913) 383-8448',
    email: 'https://orhaolam.com',
    img: ComingSoon,
  },
  {
    name: 'Adat HaTikvah Messianic Jewish Congregation',
    city: 'Louisville',
    state: 'Kentucky',
    country: 'United States',
    url: 'https://adathatikvah.com',
    phone: '(502) 551-1240',
    email: 'info@adathatikvah.com',
    img: ComingSoon,
  },
  {
    name: 'Congregation Beth Hallel',
    city: 'Mandeville',
    state: 'Louisiana',
    country: 'United States',
    url: 'https://LaMessianic.com',
    phone: '(985) 277-3109',
    email: 'info@LaMessianic.com',
    img: ComingSoon,
  },
  {
    name: 'Kehilah Portland',
    city: 'South Portland',
    state: 'Maine',
    country: 'United States',
    url: 'https://shalommaine.com',
    phone: '',
    email: 'info@jewishheritagerevival.com',
    img: ComingSoon,
  },

  {
    name: 'Ain M’Chitzah',
    city: 'Bel Air',
    state: 'Maryland',
    country: 'United States',
    url: '',
    phone: '(410) 687-1631',
    email: 'gamlingar2@yahoo.com',
    img: ComingSoon,
  },
  {
    name: 'Emmanuel Messianic Jewish Congregation',
    city: 'Clarksville',
    state: 'Maryland',
    country: 'United States',
    url: 'https://Godwithus.org',
    phone: '(410) 531-2093',
    email: '',
    img: ComingSoon,
  },
  {
    name: 'Son of David Congregation',
    city: 'Derwood',
    state: 'Maryland',
    country: 'United States',
    url: 'https://sonofdavid.org',
    phone: '(301) 963-5092',
    email: '',
    img: ComingSoon,
  },
  {
    name: 'The Tabernacle',
    city: 'Branson',
    state: 'Missouri',
    country: 'United States',
    url: 'https://TheTabernacleinBranson.com',
    phone: '(417) 334-7373',
    email: '',
    img: ComingSoon,
  },
  {
    name: 'Beit Chesed Messianic Congregation',
    city: 'St Louis',
    state: 'Missouri',
    country: 'United States',
    url: 'https://beitchesed.com',
    phone: '(314) 504-8539',
    email: 'beitchesed@gmail.com',
    img: ComingSoon,
  },
  {
    name: 'Beit Tefilah',
    city: 'St Louis',
    state: 'Missouri',
    country: 'United States',
    url: 'https://beittefilah.com',
    phone: '(314) 994-9884',
    email: 'beittefilah@juno.com',
    img: ComingSoon,
  },
  {
    name: 'Beth Tephila Messianic Jewish Congregation',
    city: 'Florence',
    state: 'Montana',
    country: 'United States',
    url: 'montanalevinsons@msn.com',
    phone: '',
    email: 'https://bethtephila.org',
    img: ComingSoon,
  },
  {
    name: 'Adat Hatikvat Tzion',
    city: 'Omaha',
    state: 'Nebraska',
    country: 'United States',
    url: 'https://Adat.org',
    phone: '(531) 484-7810',
    email: '',
    img: ComingSoon,
  },
  {
    name: 'Hope of Israel Messianic Congregation',
    city: 'Cherry Hill',
    state: 'New Jersey',
    country: 'United States',
    url: 'https://hopeofisraelnj.com',
    phone: '(856) 669-8497',
    email: 'hopeofisraelnj@gmail.com',
    img: ComingSoon,
  },
  {
    name: 'Beth Zion',
    city: 'Jackson',
    state: 'New Jersey',
    country: 'United States',
    url: 'https://bethzion.org',
    phone: '(732) 928-7700',
    email: 'info@bethzion.org',
    img: ComingSoon,
  },
  {
    name: 'Ari Yehuda Messianic Synagogue',
    city: 'Leonaro',
    state: 'New Jersey',
    country: 'United States',
    url: 'https://ariyehuda.org',
    phone: '',
    email: 'ayms@ariyehuda.org',
    img: ComingSoon,
  },
  {
    name: 'Beth Messiah Congregation',
    city: 'Livingston',
    state: 'New Jersey',
    country: 'United States',
    url: 'https://beth-messiah.org',
    phone: '(973) 994-4431',
    email: 'rabbi.irving@beth-messiah.org',
    img: ComingSoon,
  },
  {
    name: 'Beth Machaseh Messianic Congregation-',
    city: 'Williamstown',
    state: 'New Jersey',
    country: 'United States',
    url: 'https://bethmachaseh.org',
    phone: '(856) 513-6869',
    email: 'bethmachaseh@gmail.com',
    img: ComingSoon,
  },
  {
    name: 'Congregation Brith Hadoshah',
    city: 'Amherst',
    state: 'New York',
    country: 'United States',
    url: 'https://shalombuffalo.org',
    phone: '(716) 873-8986',
    email: '',
    img: ComingSoon,
  },
  {
    name: 'Shuvah Yisrael',
    city: 'Long Island',
    state: 'New York',
    country: 'United States',
    url: 'https://Shuvah.com',
    phone: '(516) 939-2277',
    email: '',
    img: ComingSoon,
  },
  {
    name: 'Congregation Sha’ar Adonai',
    city: 'Manhattan',
    state: 'New York',
    country: 'United States',
    url: 'https://shaaradonainyc.com',
    phone: '(212) 223-6751•',
    email: 'info@shaaradonai.org',
    img: ComingSoon,
  },
  {
    name: 'Congregation Sha’arei Shalom',
    city: 'Cary',
    state: 'North Carolina',
    country: 'United States',
    url: 'https://entershalom.org',
    phone: '(919) 388-3678',
    email: 'office@entershalom.org',
    img: ComingSoon,
  },
  {
    name: 'Beth Goyim',
    city: 'Lexington',
    state: 'North Carolina',
    country: 'United States',
    url: 'https://bethgoyim.org',
    phone: '(973) 338-7800',
    email: 'rabbiandrew@bethgoyim.org',
    img: ComingSoon,
  },
  {
    name: 'Rosh Pinah Messianic Congregation',
    city: 'Bath',
    state: 'Ohio',
    country: 'United States',
    url: 'https://rosh-pinah.org',
    phone: '(330) 668-6840',
    email: 'mrav.humphrey@rosh-pinah.org',
    img: ComingSoon,
  },
  {
    name: 'Beth Messiah Synagogue',
    city: 'Cincinnati',
    state: 'Ohio',
    country: 'United States',
    url: 'https://bethmessiah.net',
    phone: '(513) 683-8817',
    email: '',
    img: ComingSoon,
  },
  {
    name: 'Tikvat Yisrael Messianic Synagogue',
    city: 'Cleveland',
    state: 'Ohio',
    country: 'United States',
    url: 'https://tikvatcleveland.org',
    phone: '(216) 297-9929',
    email: 'tikvatyisrael@sbcglobal.net',
    img: ComingSoon,
  },
  {
    name: 'Beth Messiah Congregation',
    city: 'Columbus',
    state: 'Ohio',
    country: 'United States',
    url: 'https://tikvatcleveland.org',
    phone: '(216) 297-9929',
    email: 'tikvatyisrael@sbcglobal.net',
    img: ComingSoon,
  },
  {
    name: 'The S.I.T.E.',
    city: 'N Canton',
    state: 'Ohio',
    country: 'United States',
    url: 'https://starineast.org',
    phone: '(330) 491-7827',
    email: 'info@starineast.org',
    img: ComingSoon,
  },
  {
    name: 'Rosh Pinah Messianic Jewish Congregation',
    city: 'Oklahoma City',
    state: 'Oklahoma',
    country: 'United States',
    url: 'https://roshpinah.org',
    phone: '(405) 842-1967',
    email: 'info@roshpinah.org',
    img: ComingSoon,
  },
  {
    name: 'Holiness to the Lord Congregation',
    city: 'Tulsa',
    state: 'Oklahoma',
    country: 'United States',
    url: '',
    phone: '(918) 408-6689',
    email: 'gkamp31@aol.com',
    img: ComingSoon,
  },
  {
    name: 'Sa-Enu L’Tzion—Lift Us Up To Zion •',
    city: 'Bend',
    state: 'Oregon',
    country: 'United States',
    url: '',
    phone: '(541) 280-9127',
    email: 'saenultzion@gmail.com',
    img: ComingSoon,
  },
  {
    name: 'The Seed Of Abraham',
    city: 'Lancaster',
    state: 'Pensylvania',
    country: 'United States',
    url: 'https://seedofabrahampa.com',
    phone: '(717) 687-8913',
    email: 'lloyd_elias1351@comcast.net',
    img: ComingSoon,
  },
  {
    name: 'Congregation Beth Yeshua',
    city: 'Media',
    state: 'Pensylvania',
    country: 'United States',
    url: 'https://cby.org',
    phone: '(215) 477-2706',
    email: 'info@cby.org',
    img: ComingSoon,
  },
  {
    name: 'Beit Simcha Messianic Fellowship',
    city: 'Orefield',
    state: 'Pennsylvania',
    country: 'United States',
    url: 'https://beitsimcha.org',
    phone: '(610) 289-2011',
    email: '',
    img: ComingSoon,
  },
  {
    name: 'Congregation Beth Emanuel',
    city: 'Philadelphia',
    state: 'Pennsylvania',
    country: 'United States',
    url: 'https://bethemanuel.org',
    phone: '(215) 969-4569',
    email: 'rabbidavidvazquez@gmail.com',
    img: ComingSoon,
  },
  {
    name: 'Maoz Tzur-Rock of Ages Messianic Jewish Congregation',
    city: 'Pittsburgh',
    state: 'Pennsylvania',
    country: 'United States',
    url: 'https://rockofagesmjc.org',
    phone: '(412) 609-1117',
    email: '',
    img: ComingSoon,
  },
  {
    name: 'Kehilat Ari Yehudah/Congregation Lion of Judah',
    city: 'Yardley',
    state: 'Pennsylvania',
    country: 'United States',
    url: 'https://lojpa.org',
    phone: '(215) 493-4460',
    email: '',
    img: ComingSoon,
  },
  {
    name: 'Adat Netzer Matai',
    city: 'Goose Creek',
    state: 'South Carolina',
    country: 'United States',
    url: 'KHillyer@bellsouth.net',
    phone: '(843) 475-5786',
    email: '',
    img: ComingSoon,
  },
  {
    name: 'Adon Olam Messianic Congregation',
    city: 'Greenville',
    state: 'South Carolina',
    country: 'United States',
    url: 'https://adonolam.org',
    phone: '(864) 322-9144',
    email: 'aomcinfo@gmail.com',
    img: ComingSoon,
  },
  {
    name: 'Congregation Beth Shalom',
    city: 'North Augusta',
    state: 'North Carolina',
    country: 'United States',
    url: 'https://shalomaugusta.org',
    phone: '(803) 510-4143',
    email: '',
    img: ComingSoon,
  },
  {
    name: 'Ari Yehudah Congregation',
    city: 'Bristol',
    state: 'Tennese',
    country: 'United States',
    url: 'https://forzionsake.org',
    phone: '(276) 644-1678',
    email: '4znsake@earthlink.net',
    img: ComingSoon,
  },
  {
    name: 'Sukkat Shalom',
    city: 'Arlington',
    state: 'Texas',
    country: 'United States',
    url: 'https://sukkatshalom.us',
    phone: '(972) 623-2863',
    email: '',
    img: ComingSoon,
  },
  {
    name: 'Adat Shalom Messianic Congregation',
    city: 'Dallas',
    state: 'Texas',
    country: 'United States',
    url: 'https://adatshalom-dallas.org',
    phone: '(972) 271-4976',
    email: 'robin_d_rose@yahoo.com',
    img: ComingSoon,
  },
  {
    name: 'Baruch HaShem Messianic Synagogue',
    city: 'Dallas',
    state: 'Texas',
    country: 'United States',
    url: 'https://BaruchHaShemSynagogue.org',
    phone: '(972) 386-0121',
    email: 'office@bhsdallas.org',
    img: ComingSoon,
  },

  {
    name: 'Shalom, Shalom Messianic Congregation',
    city: 'Dallas',
    state: 'Texas',
    country: 'United States',
    url: 'https://brit-hadasha.org',
    phone: '(214) 356-2583',
    email: 'toddbus@yahoo.com',
    img: ComingSoon,
  },
  {
    name: 'Congregation Beth Messiah',
    city: 'Houston',
    state: 'Texas',
    country: 'United States',
    url: 'https://cbmhouston.org',
    phone: '(713) 271-5757',
    email: '',
    img: ComingSoon,
  },
  {
    name: 'Eitz Chaim',
    city: 'Plano',
    state: 'Texas',
    country: 'United States',
    url: 'https://ECDallas.org',
    phone: '(972) 231-3884',
    email: 'info@ecdallas.org',
    img: ComingSoon,
  },
  {
    name: 'Kehilat Sar Shalom',
    city: 'Leesburg',
    state: 'Virginia',
    country: 'United States',
    url: 'https://kehilatsarshalom.org',
    phone: '(443) 253-0982',
    email: 'info@kehilatsarshalom.org',
    img: ComingSoon,
  },
  {
    name: 'Congregation Zion’s Sake',
    city: 'Newport News',
    state: '',
    country: 'United States',
    url: 'https://zionsake.org',
    phone: '(757) 874-3303',
    email: 'zionsakeinfo@aol.com',
    img: ComingSoon,
  },
  {
    name: 'Beth El Messianic Congregation-',
    city: 'Port Orchard',
    state: 'Washinton',
    country: 'United States',
    url: 'https://bethelportorchardwa.com •',
    phone: '(360) 876-5581',
    email: 'bethel@bethelportorchard.com',
    img: ComingSoon,
  },
  {
    name: 'Rehoboth Messianic Congregation -',
    city: 'Vancouver',
    state: 'Washington',
    country: 'United States',
    url: 'https://rehoboth-messianic.org',
    phone: '(360) 695-2900',
    email: 'rehoboth.congregation@gmail.com',
    img: ComingSoon,
  },
  {
    name: 'Beth Messiah-Milwaukee',
    city: 'Milwaukee',
    state: 'Wisconsin',
    country: 'United States',
    url: 'https://bethmessiah.us',
    phone: '(414) 395-3043',
    email: '',
    img: ComingSoon,
  },
  {
    name: 'Beth Shechinah',
    city: 'Calgary',
    state: 'Alberta',
    country: 'Canada',
    url: 'https://bethshechinah.com',
    phone: '(403) 685-4170',
    email: 'hglory@telusplanet.net',
    img: ComingSoon,
  },
  {
    name: 'Beit Tefillah Sameach',
    city: 'Lethbridge',
    state: 'Alberta',
    country: 'Canada',
    url: '',
    phone: '(403) 634-8200',
    email: 'kehilatbeittefillah@gmail.com',
    img: ComingSoon,
  },
  {
    name: 'Shabbat Shel Shalom Messianic Fellowship',
    city: 'Greater Vancouver',
    state: 'British Columbia',
    country: 'Canada',
    url: 'https://shabbatshelshalom.com',
    phone: '(604) 996-8722',
    email: 'shabbatshelshalom@gmail.com',
    img: ComingSoon,
  },
  {
    name: 'Kehillath Tsion',
    city: 'Vancouver',
    state: 'British Columbia',
    country: 'Canada',
    url: 'https://tsion.org',
    phone: '(604) 800-3663',
    email: 'info@zmf.org',
    img: ComingSoon,
  },
  {
    name: 'Ottawa Messianic Congregation',
    city: 'Ottawa',
    state: 'Ontario',
    country: 'Canada',
    url: 'https://ottawamessianic.com',
    phone: '(613) 736-9480',
    email: '',
    img: ComingSoon,
  },
  {
    name: 'City of David',
    city: 'Thornhill',
    state: 'Ontario',
    country: 'Canada',
    url: 'https://cityofdavid.com',
    phone: '(905) 761-8118',
    email: '',
    img: ComingSoon,
  },
  {
    name: '- Kehillat ha’Derech',
    city: 'New South Wales,',
    state: 'Sydney',
    country: 'Australia',
    url: 'https://haderech.com.au',
    phone: '+61 408 426 944',
    email: 'haDerech@outlook.com.au',
    img: ComingSoon,
  },
  {
    name: 'The Messianic Jewish Community of Oradea',
    city: 'Oradea',
    state: '',
    country: 'Romania',
    url: 'https://mesianic.eu',
    phone: '+40 740 816 620',
    email: 'fcemr@mesianic.ro',
    img: ComingSoon,
  },
  {
    name: 'Friends of Jesus Christ Canada Ontario',
    city: 'Scarborough',
    state: 'Ontario',
    country: 'Canada',
    url: 'https://friendsofjesuschrist.com',
    phone: '(416) 335-8829',
    email: '',
    img: ComingSoon,
  },
  {
    name: 'Christ Community Ministries',
    city: 'Sioux Falls',
    state: 'South Dakota',
    country: 'United States',
    url: '',
    phone: '(605) 371-1889',
    email: '',
    img: ComingSoon,
  },
  {
    name: 'Free Lutheran Fellowship',
    city: 'Brownsville',
    state: 'Texas',
    country: 'United States',
    url: '',
    phone: '(956) 546-7374',
    email: '',
    img: ComingSoon,
  },
  {
    name: 'Freedom Fellowship',
    city: 'El Paso',
    state: 'Texas',
    country: 'United States',
    url: 'https://freedomfellowshipep.com',
    phone: '(915) 355-7046',
    email: 'freedomfellowshipep@gmail.com',
    img: ComingSoon,
  },
  {
    name: 'Grace Christian Center',
    city: 'El Paso',
    state: 'Texas',
    country: 'United States',
    url: 'https://gracechristianept',
    phone: '(915) 544-7400',
    email: 'lupegarcia624@att.net',
    img: ComingSoon,
  },
  {
    name: 'Gateway Church Jewish Ministry',
    city: 'Southlake',
    state: 'Texas',
    country: 'United States',
    url: 'https://gatewaypeople.com/ministries/jewish-ministry',
    phone: '',
    email: '',
    img: ComingSoon,
  },
]

/*
{
    name: '',
    city: '',
    state: '',
    country: 'United States',
    url: '',
    phone: '',
    email: '',
    img: ComingSoon,
  }, */

export const states = [
  {
    label: 'Alaska',
    abbreviation: 'AK',
  },
  {
    label: 'Arizona',
    abbreviation: 'AZ',
  },
  {
    label: 'California',
    abbreviation: 'CA',
  },
  {
    label: 'Colorado',
    abbreviation: 'CO',
  },
  {
    label: 'Connecticut',
    abbreviation: 'CT',
  },
  {
    label: 'Florida',
    abbreviation: 'FL',
  },
  {
    label: 'Georgia',
    abbreviation: 'GA',
  },
  {
    label: 'Hawaii',
    abbreviation: 'HI',
  },
  {
    label: 'Idaho',
    abbreviation: 'ID',
  },
  {
    label: 'Illinois',
    abbreviation: 'IL',
  },
  {
    label: 'Indiana',
    abbreviation: 'IN',
  },
  {
    label: 'Kansas',
    abbreviation: 'KS',
  },
  {
    label: 'Kentucky',
    abbreviation: 'KY',
  },
  {
    label: 'Louisiana',
    abbreviation: 'LA',
  },
  {
    label: 'Maine',
    abbreviation: 'ME',
  },
  {
    label: 'Maryland',
    abbreviation: 'MD',
  },
  {
    label: 'Missouri',
    abbreviation: 'MO',
  },

  {
    label: 'Montana',
    abbreviation: 'MT',
  },
  {
    label: 'Nebraska',
    abbreviation: 'NE',
  },
  {
    label: 'New Jersey',
    abbreviation: 'NJ',
  },
  {
    label: 'New York',
    abbreviation: 'NY',
  },
  {
    label: 'North Carolina',
    abbreviation: 'NC',
  },

  {
    label: 'Ohio',
    abbreviation: 'OH',
  },
  {
    label: 'Oklahoma',
    abbreviation: 'OK',
  },
  {
    label: 'Oregon',
    abbreviation: 'OR',
  },
  {
    label: 'Pennsylvania',
    abbreviation: 'PA',
  },
  {
    label: 'South Carolina',
    abbreviation: 'SC',
  },
  {
    label: 'Tennessee',
    abbreviation: 'TN',
  },
  {
    label: 'Texas',
    abbreviation: 'TX',
  },
  {
    label: 'Virginia',
    abbreviation: 'VA',
  },
  {
    label: 'Washington',
    abbreviation: 'WA',
  },

  {
    label: 'Wisconsin',
    abbreviation: 'WI',
  },
]

export const countries = [
  {
    code: 'AU',
    label: 'Australia',
    phone: '61',
    suggested: true,
  },
  {
    code: 'CA',
    label: 'Canada',
    phone: '1',
    suggested: true,
  },

  { code: 'RO', label: 'Romania', phone: '40' },

  {
    code: 'US',
    label: 'United States',
    phone: '1',
    suggested: true,
  },
]
