import AdatHallel from '../../../public/assets/congregations/AdatHallel.webp'
import BethSarShalom from '../../../public/assets/congregations/BethSarShalom.webp'
import AdatYeshua from '../../../public/assets/congregations/AdatYeshua.webp'
import Ohav from '../../../public/assets/congregations/Ohav.webp'
export const congregations = [
  {
    name: 'Adat Hallel Messianic Congregation',
    city: 'Irvine',
    state: 'California',
    country: 'United States',
    url: 'https://www.facebook.com/Adat.Hallel.Messianic/',
    phone: '',
    email: 'office@myadat.com',
    img: AdatHallel,
  },
  {
    name: 'Congregation Beth Sar Shalom',
    city: 'Tuscon',
    state: 'Arizona',
    country: 'United States',
    url: 'https://www.facebook.com/CBSSTucson/',
    phone: '(520) 326-2020',
    email: 'office@shalomtucson.org',
    img: BethSarShalom,
  },
  {
    name: "Adat Y'shua Messianic Congregation",
    city: 'West Hills',
    state: 'California',
    country: 'United States',
    url: 'https://adatyshua.org/',
    phone: ' (818) 222-0200',
    email: '',
    img: AdatYeshua,
  },
  {
    name: 'Matsu Valley Messianic Congregation',
    city: 'Wasilla',
    state: 'Alaska',
    country: 'United States',
    url: 'https://adatyshua.org/',
    phone: '',
    email: 'matsuvalleymessianic@gmail.com',
    img: '',
  },
  {
    name: 'Ohav Shalom Messianic Congregation',
    city: 'Cathedral City',
    state: 'California',
    country: 'United States',
    url: 'https://ohavshalomministries.org/',
    phone: '(760) 668-5966',
    email: 'info@ohavshalomministries.org',
    img: Ohav,
  },
  {
    name: 'Beth Emunah Messianic Synagogue',
    city: 'Agoura Hills',
    state: 'California',
    country: 'United States',
    url: 'www.bethemunah.org',
    phone: '(818) 597-9700',
    email: 'office@bethemunah.org',
    img: '',
  },
  {
    name: 'Ahava B’Shem Yeshua',
    city: 'Prescott',
    state: 'Arizona',
    country: 'United States',
    url: 'www.ahavabshemyeshua.com',
    phone: '(928) 443-5988',
    email: 'office@ahavabshemyeshua.com',
    img: '',
  },
  {
    name: 'Shiloh Messianic Congregation',
    city: 'Redlands',
    state: 'California',
    country: 'United States',
    url: 'www.shilohmessianic.com •',
    phone: '(909) 338-4846',
    email: 'shilohcongregation@gmail.com',
    img: '',
  },
  {
    name: 'Beth David Messianic Congregation',
    city: 'Fresno',
    state: 'California',
    country: 'United States',
    url: 'www.bethdavidmc.org',
    phone: '(559) 435-0106',
    email: 'info@bethdavidmc.org',
    img: '',
  },

  {
    name: 'Temple Aviv Judea',
    city: 'Fullerton',
    state: 'California',
    country: 'United States',
    url: 'www.avivjudea.org',
    phone: '(714) 748-4504',
    email: 'info@avivjudea.org',
    img: '',
  },
  {
    name: 'Beit David Messianic Fellowship',
    city: 'Long Beach',
    state: 'California',
    country: 'United States',
    url: 'www.Beit-David.org',
    phone: '',
    email: 'beit.david@yahoo.com',
    img: '',
  },
  {
    name: 'Ben David Messianic Jewish Congregation',
    city: 'Orange',
    state: 'California',
    country: 'United States',
    url: 'www.BenDavidMJC.org',
    phone: '(949) 551-2659',
    email: 'info@BenDavidMJC.org',
    img: '',
  },
  {
    name: 'Kehilat Ariel',
    city: 'San Diego',
    state: 'California',
    country: 'United States',
    url: 'www.kehilatariel.org',
    phone: '(858) 430-6433',
    email: '',
    img: '',
  },
  {
    name: 'Tree of Life Messianic Congregation',
    city: 'San Diego',
    state: 'California',
    country: 'United States',
    url: 'www.treeoflifeca.org',
    phone: '',
    email: 'ravjoel@pacbell.net',
    img: '',
  },

  {
    name: 'Congregation Roeh Israel',
    city: 'Denver',
    state: 'Colorado',
    country: 'United States',
    url: 'www.roehisrael.com',
    phone: '(303) 337-6254',
    email: 'roehisraeldenver@gmail.com',
    img: '',
  },
  {
    name: 'Congregation Yeshuat Tsion',
    city: 'Greenwood Village',
    state: 'Colorado',
    country: 'United States',
    url: 'www.yeshuattsion.org',
    phone: '(303) 740-5413',
    email: '',
    img: '',
  },
  {
    name: 'Congregation Simchat Yisrael',
    city: 'West Haven',
    state: 'Connecticut',
    country: 'United States',
    url: 'www.simchatyisrael.org',
    phone: '(203) 932-9929',
    email: 'office@simchatyisrael.org',
    img: '',
  },
  {
    name: 'Ohr Chadash',
    city: 'Clearwater',
    state: 'Florida',
    country: 'United States',
    url: 'www.ohrchadash.org',
    phone: '(727) 726-1472',
    email: '',
    img: '',
  },
  {
    name: 'Temple Aron HaKodesh',
    city: 'Fort Lauderdale',
    state: 'Florida',
    country: 'United States',
    url: 'www.tak.org',
    phone: '(954) 485-8491',
    email: '',
    img: '',
  },
  {
    name: 'Etz Chayim Messianic Synagogue',
    city: 'Lakeland',
    state: 'Florida',
    country: 'United States',
    url: 'www.myetzchayim.org',
    phone: '(863) 274-6141',
    email: '',
    img: '',
  },

  {
    name: 'Mishkan Messianic Congregation',
    city: 'Ocala',
    state: 'Florida',
    country: 'United States',
    url: '',
    phone: '(352) 687-4434',
    email: 'mishkanmessianiccongregation@yahoo.com',
    img: '',
  },
  {
    name: 'Kerem El Messianic Synagogue',
    city: 'Port St. Lucie',
    state: 'California',
    country: 'United States',
    url: 'www.keremel.org',
    phone: '(772) 621-7812',
    email: '',
    img: '',
  },
  {
    name: 'Shoresh David Messianic Synagogue',
    city: 'St Petersburg',
    state: 'California',
    country: 'United States',
    url: 'www.shoreshdavid.org',
    phone: '(813) 831-5673',
    email: '',
    img: '',
  },
  {
    name: 'Shoresh David Messianic Synagogue',
    city: 'Tampa',
    state: 'Florida',
    country: 'United States',
    url: 'www.shoreshdavid.org',
    phone: '(813) 760-3269',
    email: '',
    img: '',
  },
  {
    name: 'Shoresh David Messianic Synagogue',
    city: 'Wesley Chapel',
    state: 'California',
    country: 'United States',
    url: 'www.shoreshdavid.org',
    phone: '(813) 760-3269',
    email: 'emarvin@shoreshdavid.org',
    img: '',
  },
  {
    name: 'Congregation Beth Hallel',
    city: 'Roswell',
    state: 'Georgia',
    country: 'United States',
    url: 'www.bethhallel.org',
    phone: '(770) 641-3000',
    email: 'emarvin@shoreshdavid.org',
    img: '',
  },
  {
    name: 'Beit Shalom Messianic Synagogue',
    city: 'Thomasville',
    state: 'Georgia',
    country: 'United States',
    url: 'www.beitshalom.us',
    phone: '(229) 327-6060',
    email: 'info.bsms.ga@gmail.com',
    img: '',
  },
  {
    name: 'Tikvat Yisrael',
    city: 'Honolulu',
    state: 'Hawaii',
    country: 'United States',
    url: 'www.TikvatYisrael.com',
    phone: '(808) 351-6364',
    email: '',
    img: '',
  },
  {
    name: 'The Bridge Messianic Fellowship',
    city: 'Boise',
    state: 'Idaho',
    country: 'United States',
    url: 'www.thebridgeidaho.com',
    phone: '(208) 994-3642',
    email: 'hello@thebridgeidaho.com',
    img: '',
  },
  {
    name: 'Rock of Israel Messianic Congregation',
    city: 'Long Grove',
    state: 'Illinois',
    country: 'United States',
    url: 'www.rockofisrael.net',
    phone: '(847) 507-4260',
    email: 'rschwarcz@chosenpeople.com',
    img: '',
  },
  {
    name: 'Olive Tree Congregation',
    city: 'Prospect Heights',
    state: 'Illinois',
    country: 'United States',
    url: 'www.olive-tree.org',
    phone: '(847) 222-1230',
    email: 'olivetreechicago@gmail.com',
    img: '',
  },
  {
    name: 'Congregation Shaarey Yeshua',
    city: 'Indianapolis',
    state: 'Indiana',
    country: 'United States',
    url: 'www.shaareyyeshua.org',
    phone: '(327) 202-0789',
    email: 'office@shaareyyeshua.org',
    img: '',
  },

  {
    name: 'Or HaOlam Messianic Synagogue',
    city: 'Overland Park',
    state: 'Kansas',
    country: 'United States',
    url: '',
    phone: '(913) 383-8448',
    email: 'www.orhaolam.com',
    img: '',
  },
  {
    name: 'Adat HaTikvah Messianic Jewish Congregation',
    city: 'Louisville',
    state: 'Kentucky',
    country: 'United States',
    url: 'www.adathatikvah.com',
    phone: '(502) 551-1240',
    email: 'info@adathatikvah.com',
    img: '',
  },
  {
    name: 'Congregation Beth Hallel',
    city: 'Mandeville',
    state: 'Louisiana',
    country: 'United States',
    url: 'www.LaMessianic.com',
    phone: '(985) 277-3109',
    email: 'info@LaMessianic.com',
    img: '',
  },
  {
    name: 'Kehilah Portland',
    city: 'South Portland',
    state: 'Maine',
    country: 'United States',
    url: 'www.shalommaine.com',
    phone: '',
    email: 'info@jewishheritagerevival.com',
    img: '',
  },

  {
    name: 'Ain M’Chitzah',
    city: 'Bel Air',
    state: 'Maryland',
    country: 'United States',
    url: '',
    phone: '(410) 687-1631',
    email: 'gamlingar2@yahoo.com',
    img: '',
  },
  {
    name: 'Emmanuel Messianic Jewish Congregation',
    city: 'Clarksville',
    state: 'Maryland',
    country: 'United States',
    url: 'www.Godwithus.org',
    phone: '(410) 531-2093',
    email: '',
    img: '',
  },
  {
    name: 'Son of David Congregation',
    city: 'Derwood',
    state: 'Maryland',
    country: 'United States',
    url: 'www.sonofdavid.org',
    phone: '(301) 963-5092',
    email: '',
    img: '',
  },
  {
    name: 'The Tabernacle',
    city: 'Branson',
    state: 'Missouri',
    country: 'United States',
    url: 'www.TheTabernacleinBranson.com',
    phone: '(417) 334-7373',
    email: '',
    img: '',
  },
  {
    name: 'Beit Chesed Messianic Congregation',
    city: 'St Louis',
    state: 'Missouri',
    country: 'United States',
    url: 'www.beitchesed.com',
    phone: '(314) 504-8539',
    email: 'beitchesed@gmail.com',
    img: '',
  },
  {
    name: 'Beit Tefilah',
    city: 'St Louis',
    state: 'Missouri',
    country: 'United States',
    url: 'www.beittefilah.com',
    phone: '(314) 994-9884',
    email: 'beittefilah@juno.com',
    img: '',
  },
  {
    name: 'Beth Tephila Messianic Jewish Congregation',
    city: 'Florence',
    state: 'Montana',
    country: 'United States',
    url: 'montanalevinsons@msn.com',
    phone: '',
    email: 'www.bethtephila.org',
    img: '',
  },
  {
    name: 'Adat Hatikvat Tzion',
    city: 'Omaha',
    state: 'Nebraska',
    country: 'United States',
    url: 'www.Adat.org',
    phone: '(531) 484-7810',
    email: '',
    img: '',
  },
  {
    name: 'Hope of Israel Messianic Congregation',
    city: 'Cherry Hill',
    state: 'New Jersey',
    country: 'United States',
    url: 'www.hopeofisraelnj.com',
    phone: '(856) 669-8497',
    email: 'hopeofisraelnj@gmail.com',
    img: '',
  },
  {
    name: 'Beth Zion',
    city: 'Jackson',
    state: 'New Jersey',
    country: 'United States',
    url: 'www.bethzion.org',
    phone: '(732) 928-7700',
    email: 'info@bethzion.org',
    img: '',
  },
  {
    name: 'Ari Yehuda Messianic Synagogue',
    city: 'Leonaro',
    state: 'New Jersey',
    country: 'United States',
    url: 'www.ariyehuda.org',
    phone: '',
    email: 'ayms@ariyehuda.org',
    img: '',
  },
  {
    name: 'Beth Messiah Congregation',
    city: 'Livingston',
    state: 'New Jersey',
    country: 'United States',
    url: 'www.beth-messiah.org',
    phone: '(973) 994-4431',
    email: 'rabbi.irving@beth-messiah.org',
    img: '',
  },
  {
    name: 'Beth Machaseh Messianic Congregation-',
    city: 'Williamstown',
    state: 'New Jersey',
    country: 'United States',
    url: 'www.bethmachaseh.org',
    phone: '(856) 513-6869',
    email: 'bethmachaseh@gmail.com',
    img: '',
  },
  {
    name: 'Congregation Brith Hadoshah',
    city: 'Amherst',
    state: 'New York',
    country: 'United States',
    url: 'www.shalombuffalo.org',
    phone: '(716) 873-8986',
    email: '',
    img: '',
  },
  {
    name: 'Shuvah Yisrael',
    city: 'Long Island',
    state: 'New York',
    country: 'United States',
    url: 'www.Shuvah.com',
    phone: '(516) 939-2277',
    email: '',
    img: '',
  },
  {
    name: 'Congregation Sha’ar Adonai',
    city: 'Manhattan',
    state: 'New York',
    country: 'United States',
    url: 'www.shaaradonainyc.com',
    phone: '(212) 223-6751•',
    email: 'info@shaaradonai.org',
    img: '',
  },
  {
    name: 'Congregation Sha’arei Shalom',
    city: 'Cary',
    state: 'North Carolina',
    country: 'United States',
    url: 'www.entershalom.org',
    phone: '(919) 388-3678',
    email: 'office@entershalom.org',
    img: '',
  },
  {
    name: 'Beth Goyim',
    city: 'Lexington',
    state: 'North Carolina',
    country: 'United States',
    url: 'www.bethgoyim.org',
    phone: '(973) 338-7800',
    email: 'rabbiandrew@bethgoyim.org',
    img: '',
  },
  {
    name: 'Rosh Pinah Messianic Congregation',
    city: 'Bath',
    state: 'Ohio',
    country: 'United States',
    url: 'www.rosh-pinah.org',
    phone: '(330) 668-6840',
    email: 'mrav.humphrey@rosh-pinah.org',
    img: '',
  },
  {
    name: 'Beth Messiah Synagogue',
    city: 'Cincinnati',
    state: 'Ohio',
    country: 'United States',
    url: 'www.bethmessiah.net',
    phone: '(513) 683-8817',
    email: '',
    img: '',
  },
  {
    name: 'Tikvat Yisrael Messianic Synagogue',
    city: 'Cleveland',
    state: 'Ohio',
    country: 'United States',
    url: 'www.tikvatcleveland.org',
    phone: '(216) 297-9929',
    email: 'tikvatyisrael@sbcglobal.net',
    img: '',
  },
  {
    name: 'Beth Messiah Congregation',
    city: 'Columbus',
    state: 'Ohio',
    country: 'United States',
    url: 'www.tikvatcleveland.org',
    phone: '(216) 297-9929',
    email: 'tikvatyisrael@sbcglobal.net',
    img: '',
  },
  {
    name: 'The S.I.T.E.',
    city: 'N Canton',
    state: 'Ohio',
    country: 'United States',
    url: 'www.starineast.org',
    phone: '(330) 491-7827',
    email: 'info@starineast.org',
    img: '',
  },
  {
    name: 'Rosh Pinah Messianic Jewish Congregation',
    city: 'Oklahoma City',
    state: 'Oklahoma',
    country: 'United States',
    url: 'www.roshpinah.org',
    phone: '(405) 842-1967',
    email: 'info@roshpinah.org',
    img: '',
  },
  {
    name: 'Holiness to the Lord Congregation',
    city: 'Tulsa',
    state: 'Oklahoma',
    country: 'United States',
    url: '',
    phone: '(918) 408-6689',
    email: 'gkamp31@aol.com',
    img: '',
  },
  {
    name: 'Sa-Enu L’Tzion—Lift Us Up To Zion •',
    city: 'Bend',
    state: 'Oregon',
    country: 'United States',
    url: '',
    phone: '(541) 280-9127',
    email: 'saenultzion@gmail.com',
    img: '',
  },
  {
    name: 'The Seed Of Abraham',
    city: 'Lancaster',
    state: 'Pensylvania',
    country: 'United States',
    url: 'www.seedofabrahampa.com',
    phone: '(717) 687-8913',
    email: 'lloyd_elias1351@comcast.net',
    img: '',
  },
  {
    name: 'Congregation Beth Yeshua',
    city: 'Media',
    state: 'Pensylvania',
    country: 'United States',
    url: 'www.cby.org',
    phone: '(215) 477-2706',
    email: 'info@cby.org',
    img: '',
  },
  {
    name: 'Beit Simcha Messianic Fellowship',
    city: 'Orefield',
    state: 'Pennsylvania',
    country: 'United States',
    url: 'www.beitsimcha.org',
    phone: '(610) 289-2011',
    email: '',
    img: '',
  },
  {
    name: 'Congregation Beth Emanuel',
    city: 'Philadelphia',
    state: 'Pennsylvania',
    country: 'United States',
    url: 'www.bethemanuel.org',
    phone: '(215) 969-4569 •',
    email: 'rabbidavidvazquez@gmail.com',
    img: '',
  },
  {
    name: 'Maoz Tzur-Rock of Ages Messianic Jewish Congregation',
    city: 'Pittsburgh',
    state: 'Pennsylvania',
    country: 'United States',
    url: 'www.rockofagesmjc.org',
    phone: '(412) 609-1117',
    email: '',
    img: '',
  },
  {
    name: 'Kehilat Ari Yehudah/Congregation Lion of Judah',
    city: 'Yardley',
    state: 'Pennsylvania',
    country: 'United States',
    url: 'www.lojpa.org',
    phone: '(215) 493-4460',
    email: '',
    img: '',
  },
  {
    name: 'Adat Netzer Matai',
    city: 'Goose Creek',
    state: 'South Carolina',
    country: 'United States',
    url: 'KHillyer@bellsouth.net',
    phone: '(843) 475-5786',
    email: '',
    img: '',
  },
  {
    name: 'Adon Olam Messianic Congregation',
    city: 'Greenville',
    state: 'South Carolina',
    country: 'United States',
    url: 'www.adonolam.org',
    phone: '(864) 322-9144',
    email: 'aomcinfo@gmail.com',
    img: '',
  },
  {
    name: 'Congregation Beth Shalom',
    city: 'North Augusta',
    state: 'North Carolina',
    country: 'United States',
    url: 'www.shalomaugusta.org',
    phone: '(803) 510-4143',
    email: '',
    img: '',
  },
  {
    name: 'Ari Yehudah Congregation',
    city: 'Bristol',
    state: 'Tennese',
    country: 'United States',
    url: 'www.forzionsake.org',
    phone: '(276) 644-1678',
    email: '4znsake@earthlink.net',
    img: '',
  },
  {
    name: 'Sukkat Shalom',
    city: 'Arlington',
    state: 'Texas',
    country: 'United States',
    url: 'www.sukkatshalom.us',
    phone: '(972) 623-2863',
    email: '',
    img: '',
  },
  {
    name: 'Adat Shalom Messianic Congregation',
    city: 'Dallas',
    state: 'Texas',
    country: 'United States',
    url: 'www.adatshalom-dallas.org',
    phone: '(972) 271-4976',
    email: 'robin_d_rose@yahoo.com',
    img: '',
  },
  {
    name: 'Baruch HaShem Messianic Synagogue',
    city: 'Dallas',
    state: 'Texas',
    country: 'United States',
    url: 'www.BaruchHaShemSynagogue.org',
    phone: '(972) 386-0121',
    email: 'office@bhsdallas.org',
    img: '',
  },

  {
    name: 'Shalom, Shalom Messianic Congregation',
    city: 'Dallas',
    state: 'Texas',
    country: 'Inited States',
    url: 'www.brit-hadasha.org',
    phone: '(214) 356-2583',
    email: 'toddbus@yahoo.com',
    img: '',
  },
  {
    name: 'Congregation Beth Messiah',
    city: 'Houston',
    state: 'Texas',
    country: 'Inited States',
    url: 'www.cbmhouston.org',
    phone: '(713) 271-5757',
    email: '',
    img: '',
  },
  {
    name: 'Eitz Chaim',
    city: 'Plano',
    state: 'Texas',
    country: 'Inited States',
    url: 'www.ECDallas.org',
    phone: '(972) 231-3884',
    email: 'info@ecdallas.org',
    img: '',
  },
  {
    name: 'Kehilat Sar Shalom',
    city: 'Leesburg',
    state: 'Virginia',
    country: 'Inited States',
    url: 'www.kehilatsarshalom.org',
    phone: '(443) 253-0982',
    email: 'info@kehilatsarshalom.org',
    img: '',
  },
  {
    name: 'Congregation Zion’s Sake',
    city: 'Newport News',
    state: '',
    country: 'Inited States',
    url: 'www.zionsake.org',
    phone: '(757) 874-3303',
    email: 'zionsakeinfo@aol.com',
    img: '',
  },
  {
    name: 'Beth El Messianic Congregation-',
    city: 'Port Orchard',
    state: 'Washinton',
    country: 'Inited States',
    url: 'www.bethelportorchardwa.com •',
    phone: '(360) 876-5581',
    email: 'bethel@bethelportorchard.com',
    img: '',
  },
  {
    name: 'Rehoboth Messianic Congregation -',
    city: 'Vancouver',
    state: 'Washington',
    country: 'Inited States',
    url: 'www.rehoboth-messianic.org',
    phone: '(360) 695-2900',
    email: 'rehoboth.congregation@gmail.com',
    img: '',
  },
  {
    name: 'Beth Messiah-Milwaukee',
    city: 'Milwaukee',
    state: 'Wisconsin',
    country: 'Inited States',
    url: 'www.bethmessiah.us',
    phone: '(414) 395-3043',
    email: '',
    img: '',
  },
]

/*
{
    name: '',
    city: '',
    state: '',
    country: 'Inited States',
    url: '',
    phone: '',
    email: '',
    img: '',
  }, */

export const states = [
  {
    label: 'Alaska',
    abbreviation: 'AK',
  },
  {
    label: 'Arizona',
    abbreviation: 'AZ',
  },
  {
    label: 'California',
    abbreviation: 'CA',
  },
  {
    label: 'Colorado',
    abbreviation: 'CO',
  },
  {
    label: 'Connecticut',
    abbreviation: 'CT',
  },
  {
    label: 'Florida',
    abbreviation: 'FL',
  },
  {
    label: 'Georgia',
    abbreviation: 'GA',
  },
  {
    label: 'Hawaii',
    abbreviation: 'HI',
  },
  {
    label: 'Idaho',
    abbreviation: 'ID',
  },
  {
    label: 'Illinois',
    abbreviation: 'IL',
  },
  {
    label: 'Indiana',
    abbreviation: 'IN',
  },
  {
    label: 'Kansas',
    abbreviation: 'KS',
  },
  {
    label: 'Kentucky',
    abbreviation: 'KY',
  },
  {
    label: 'Louisiana',
    abbreviation: 'LA',
  },
  {
    label: 'Maine',
    abbreviation: 'ME',
  },
  {
    label: 'Maryland',
    abbreviation: 'MD',
  },
  {
    label: 'Missouri',
    abbreviation: 'MO',
  },

  {
    label: 'Montana',
    abbreviation: 'MT',
  },
  {
    label: 'Nebraska',
    abbreviation: 'NE',
  },
  {
    label: 'New Jersey',
    abbreviation: 'NJ',
  },
  {
    label: 'New York',
    abbreviation: 'NY',
  },
  {
    label: 'North Carolina',
    abbreviation: 'NC',
  },

  {
    label: 'Ohio',
    abbreviation: 'OH',
  },
  {
    label: 'Oklahoma',
    abbreviation: 'OK',
  },
  {
    label: 'Oregon',
    abbreviation: 'OR',
  },
  {
    label: 'Pennsylvania',
    abbreviation: 'PA',
  },
  {
    label: 'South Carolina',
    abbreviation: 'SC',
  },
  {
    label: 'Tennessee',
    abbreviation: 'TN',
  },
  {
    label: 'Texas',
    abbreviation: 'TX',
  },
  {
    label: 'Virginia',
    abbreviation: 'VA',
  },
  {
    label: 'Washington',
    abbreviation: 'WA',
  },

  {
    label: 'Wisconsin',
    abbreviation: 'WI',
  },
]
